- name: ACIBOOTSTRAP Tests
  hosts: apic
  connection: local
  gather_facts: no
  vars_files:
    - acibootstrap/files/vars/acibootstrap_vars.yml
    - acibootstrap/files/vars/static_vars.yml

  tasks:
    - name: debug
      debug: msg="{{ vars }}"
    - name: create {{ tenant.name }} routed out
      template: src={{ templates }}/out-tenant-routed-out.j2 dest={{ dynamic }}/out-{{ tenant.name }}-routed-out.json
    - name: install {{ tenant.name }} routed out
      aci_rest: action=post uri=api/mo/uni.json config_file={{ dynamic }}/out-{{ enant.name }}-routed-out.json host={{ inventory_hostname }} username={{ user }} password={{ pass }} protocol={{ protocol }}
