- name: ACIBOOTSTRAP Tests
  hosts: apic
  connection: local
  gather_facts: no

  tasks:
  #  - name: Leafs
#      aci_leaf: host={{ inventory_hostname }} username={{ user }} password={{ pass }}
#      register: leafs#
#
#    - name: debug
  #    debug: var=leafs.response

    - name: spines
      aci_spine_id.py: host={{ inventory_hostname }} username={{ user }} password={{ pass }}
      register: spines

    - name: spine debug
      debug: var=spines.response


    - name: debug
      debug: msg="{{ vars }}"